import { GoogleGenAI, Modality } from '@google/genai';
import { fileToBase64, getMimeType } from '../utils/fileUtils';

interface ModelConfig {
  temperature: number;
  topK: number;
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateBackground = async (
  prompt: string,
  imageFiles: File[],
  modelConfig: ModelConfig
): Promise<string[]> => {
  const model = 'gemini-2.5-flash-image';

  // Convert all files to base64 inline parts
  const imageParts = await Promise.all(
    imageFiles.map(async (file) => {
      const base64Image = await fileToBase64(file);
      const mimeType = getMimeType(file.name) || 'image/jpeg';
      return {
        inlineData: {
          data: base64Image,
          mimeType,
        },
      };
    })
  );

  // Construct a smart prompt for the AI depending on the number of images
  let finalPrompt = '';
  if (imageFiles.length === 1) {
    finalPrompt = `Please replace the background of this image with the following description, ensuring the main subject or product is perfectly preserved, well-lighted, and the output is a highly realistic composite image. Background description: ${prompt}`;
  } else {
    finalPrompt = `You are a professional graphic compositor. Combine, merge, and blend elements/subjects from the attached ${imageFiles.length} images into a single highly realistic, cohesive composite image. Carefully read the blending instructions and follow them. Ensure natural lighting, realistic shadows, cohesive perspective, and keep details of the original subjects accurate.

Blending instructions and environment description:
${prompt}

Mapping of the attached images:
`;
    imageFiles.forEach((file, index) => {
      finalPrompt += `- Attached Image #${index + 1} (Referred to as "عکس ${index + 1}" or "تصویر ${index + 1}"): ${file.name}\n`;
    });
  }

  const textPart = {
    text: finalPrompt,
  };

  const generateSingleImage = async (): Promise<string> => {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        // Pass all images as individual parts followed by the text part
        parts: [...imageParts, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
        temperature: modelConfig.temperature,
        topK: modelConfig.topK,
      },
    });

    if (
      response.candidates &&
      response.candidates[0].content.parts[0].inlineData
    ) {
      const generatedImagePart = response.candidates[0].content.parts[0];
      const base64Data = generatedImagePart.inlineData.data;
      const imageMimeType = generatedImagePart.inlineData.mimeType;
      return `data:${imageMimeType};base64,${base64Data}`;
    } else {
      throw new Error('No image was generated by the API.');
    }
  };

  try {
    // Generate 5 distinct variations in parallel to offer the user diverse results
    const promises = Array(5)
      .fill(0)
      .map(() => generateSingleImage());
    const results = await Promise.all(promises);
    return results;
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error('Failed to generate composite images from Gemini API.');
  }
};
